# Generated by Django 3.0.4 on 2020-05-12 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='district',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=100)),
                ('_prefix', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=50)),
                ('_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=100)),
                ('_prefix', models.CharField(max_length=20)),
                ('_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiaChi.district')),
                ('_province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiaChi.province')),
            ],
        ),
        migrations.CreateModel(
            name='street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=100)),
                ('_prefix', models.CharField(max_length=20)),
                ('_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiaChi.district')),
                ('_province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiaChi.province')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='_province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiaChi.province'),
        ),
    ]
