# Generated by Django 3.0.4 on 2020-05-10 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('District_Ward', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MotelTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeMotel', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Motel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Image', models.ImageField(default='images.jpg', upload_to='')),
                ('Price', models.IntegerField(default=0)),
                ('Address', models.CharField(max_length=100)),
                ('PostDate', models.DateField(default=django.utils.timezone.now)),
                ('Update', models.DateField(default=django.utils.timezone.now)),
                ('NumberPhone', models.IntegerField(default=0)),
                ('Area', models.IntegerField(default=0)),
                ('Content', models.TextField(max_length=1000)),
                ('idDistrict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='District_Ward.District')),
                ('idType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Motel.MotelTypes')),
                ('idWard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='District_Ward.Ward')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PhongTro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
