# Generated by Django 3.0.4 on 2020-05-10 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Motel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motel',
            name='idType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Motel.MotelTypes'),
        ),
    ]
