# Generated by Django 3.0.6 on 2020-05-22 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DiaChi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DichVu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhongTro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TieuDe', models.CharField(max_length=100)),
                ('Anh', models.ImageField(default='images.jpg', upload_to='')),
                ('Gia', models.DecimalField(decimal_places=3, max_digits=20)),
                ('NgayDang', models.DateField(default=django.utils.timezone.now)),
                ('SDT', models.IntegerField(default=0)),
                ('DienTich', models.IntegerField(default=0)),
                ('NoiDung', models.TextField(max_length=1000)),
                ('DichVu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DichVu.DichVu')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiaChi.district')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PhongTro', to=settings.AUTH_USER_MODEL)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiaChi.province')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiaChi.street')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiaChi.ward')),
            ],
        ),
    ]
