# Generated by Django 3.0.4 on 2020-06-01 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=100)),
                ('_prefix', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=50)),
                ('_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=100)),
                ('_prefix', models.CharField(max_length=20)),
                ('_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.District')),
                ('_province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.Province')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=100)),
                ('_prefix', models.CharField(max_length=20)),
                ('_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.District')),
                ('_province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.Province')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='_province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='local.Province'),
        ),
    ]
